name: Render R Markdown and Push to New Branch

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  render-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push using GITHUB_TOKEN

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev \
                                  libfontconfig1-dev libharfbuzz-dev libfribidi-dev \
                                  libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev \
                                  pandoc

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("remotes", "rmarkdown"), repos="https://cloud.r-project.org", dependencies=TRUE)'
          Rscript -e 'remotes::install_cran(c("plotly", "lubridate", "akima", "stringr", "tidyr", "dplyr"), dependencies=TRUE)'

      - name: Render R Markdown
        run: |
          Rscript -e 'rmarkdown::render("3d_heatmap_with_gtihub.Rmd")'

      - name: Push rendered HTML to new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Generate a timestamped branch name
          BRANCH_NAME="rendered-output-$(date -u +'%Y%m%d-%H%M%S')"
          
          git checkout -b "$BRANCH_NAME"
          git add 3d_heatmap_with_gtihub.html
          git commit -m "Add rendered HTML output"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} "$BRANCH_NAME"

